#!/bin/sh
set -eu
SHA="${1:?commit sha required}"
ROOT="/home/u878466595/domains/hositee.com/public_html/etizan-law"
TMP="/home/u878466595/.etizan-deploy-${SHA}"
ZIP="/home/u878466595/.etizan-${SHA}.zip"
URL="https://codeload.github.com/marketinghorizonssa-alt/Etizan/zip/${SHA}"
REF="https://www.etizan-law.com"
rm -rf "$TMP" "$ZIP"
mkdir -p "$TMP" "$ROOT"
curl -fsSL "$URL" -o "$ZIP"
unzip -q "$ZIP" -d "$TMP"
SRC=$(find "$TMP" -mindepth 1 -maxdepth 1 -type d | head -n 1)
test -f "$SRC/index.php"
test -f "$SRC/app/config.php"
test -f "$SRC/public/assets/site.css"
test -f "$SRC/public/assets/perf.css"
test -f "$SRC/scripts/build-brand-assets.php"
mkdir -p "$ROOT/app" "$ROOT/assets"
cp -f "$SRC/index.php" "$SRC/.htaccess" "$ROOT/"
cp -f "$SRC/app/"*.php "$ROOT/app/"
cp -f "$SRC/public/assets/"* "$ROOT/assets/"
sed -i 's#site.js?v=11#site.js?v=13#g' "$ROOT/app/view.php"
curl -fsSL "$REF/logo.png" -o "$TMP/logo.png"
curl -fsSL "$REF/hero-bg-wide-gavel.png" -o "$TMP/hero.png"
curl -fsSL "$REF/about-image.png" -o "$TMP/about.png"
php "$SRC/scripts/build-brand-assets.php" "$TMP/logo.png" "$TMP/hero.png" "$TMP/about.png" "$ROOT/assets"
test -s "$ROOT/assets/logo-brand.webp"
test -s "$ROOT/assets/hero-bg.webp"
test -s "$ROOT/assets/hero-bg-mobile.webp"
test -s "$ROOT/assets/about-image.webp"
test -s "$ROOT/assets/about-image-mobile.webp"
grep -Fq '/assets/site.js?v=13' "$ROOT/app/view.php"
printf '%s\n' "$SHA" > "$ROOT/RELEASE"
rm -rf "$TMP" "$ZIP"
printf 'ETIZAN_DEPLOY_OK:%s\n' "$SHA"
