'use strict';
const {GTM,CALL,services,pages}=require('./config');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function pageData(reqPath){
 const parts=reqPath.split('/').filter(Boolean); const cityEn=parts[0]==='jeddah'?'jeddah':'riyadh'; const city=cityEn==='jeddah'?'جدة':'الرياض'; const key=pages[parts[1]]?parts[1]:'general'; const p=pages[key]; const r=s=>s.replaceAll('%CITY%',city); return {cityEn,city,key,p,title:r(p.title),h1:r(p.h1),lead:r(p.lead),keywords:p.keywords.map(r),wa:cityEn==='jeddah'?'966559451110':'966552491110'};
}
function html(reqPath){
 const x=pageData(reqPath); const canonical=`https://etizan.hositee.com/${x.cityEn}/${x.key==='general'?'':x.key+'/'}`; const description=(x.lead+' اطلب تواصلًا قانونيًا من شركة إتزان للمحاماة والاستشارات القانونية.').slice(0,160); const opts=services.map(s=>`<option value="${esc(s)}"${s===x.p.service?' selected':''}>${esc(s)}</option>`).join('');
 return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(x.title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta name="theme-color" content="#172524"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/site.css?v=5" as="style"><link rel="stylesheet" href="/assets/site.css?v=5"><script>window.dataLayer=window.dataLayer||[];</script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${GTM}');</script></head><body data-city="${x.city}" data-service="${esc(x.p.service)}" data-wa="${x.wa}"><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${GTM}" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<header class="topbar"><div class="wrap nav"><a class="brand" href="/${x.cityEn}/"><img src="/assets/logo.svg" width="172" height="54" alt="إتزان للمحاماة"></a><div class="nav-actions"><a class="ghost track-call" href="tel:+${CALL}">اتصال</a><a class="solid track-wa" href="https://wa.me/${x.wa}?text=${encodeURIComponent('السلام عليكم، أرغب في استشارة قانونية لدى إتزان.')}">تواصل واتساب</a></div></div></header>
<main><section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><div class="eyebrow">شركة إتزان للمحاماة والاستشارات القانونية · ${x.city}</div><h1>${esc(x.h1)}</h1><p class="lead">${esc(x.lead)}</p><div class="keyword-row">${x.keywords.map(k=>`<span>${esc(k)}</span>`).join('')}</div><div class="trust"><div><strong>خدمة قانونية متخصصة</strong><small>فهم الملف قبل تحديد المسار</small></div><div><strong>خصوصية ووضوح</strong><small>بياناتك تستخدم لغرض التواصل القانوني</small></div><div><strong>الرياض وجدة</strong><small>توجيه الطلب للفرع المناسب</small></div></div><div class="legal-art"><svg viewBox="0 0 620 170"><path d="M60 122C155 22 257 16 351 83s163 44 214-5"/><circle cx="146" cy="69" r="34"/><path d="M146 35v87M112 67h68M112 67l-22 44h44l-22-44M180 67l-22 44h44l-22-44"/><path d="M408 35h112M464 35v91M424 126h80"/></svg></div></div>
<div class="form-card" id="contact-form"><div class="form-head"><span>طلب تواصل قانوني</span><strong>اترك بياناتك وسيتم توجيهها لفرع ${x.city}</strong></div><form id="leadForm" novalidate><input type="hidden" name="service" value="${esc(x.p.service)}"><input type="hidden" name="city" value="${x.city}"><input type="hidden" name="consent" value="نعم"><input type="hidden" name="consent_version" value="v1"><label>الاسم الكامل<input name="name" autocomplete="name" required minlength="2" placeholder="الاسم"></label><label>رقم الجوال<input name="phone" inputmode="tel" autocomplete="tel" required placeholder="05xxxxxxxx"></label><label>الخدمة المطلوبة<select name="service_select" id="serviceSelect">${opts}</select></label><label>ملخص مختصر <span>(اختياري)</span><textarea name="message" rows="3" placeholder="اكتب نبذة مختصرة عن الموضوع"></textarea></label><label class="consent"><input type="checkbox" id="consentCheck" checked required><span>أوافق على استخدام بياناتي للتواصل بخصوص الطلب وفق <a href="https://www.etizan-law.com/privacy" target="_blank" rel="noopener">سياسة الخصوصية</a>.</span></label><button type="submit" class="submit">إرسال الطلب</button><div class="form-status" id="formStatus" role="status" aria-live="polite"></div></form></div></div></section>
<section class="services"><div class="wrap"><div class="section-kicker">خدمة مرتبطة مباشرة بهدف بحثك</div><h2>ما الذي يمكن أن نساعدك فيه؟</h2><div class="cards">${x.p.cards.map(c=>`<article><h3>${esc(c[0])}</h3><p>${esc(c[1])}</p></article>`).join('')}</div></div></section><section class="process"><div class="wrap process-grid"><div><div class="section-kicker">مسار واضح من أول تواصل</div><h2>ابدأ بالمعلومات الأساسية، ثم نحدد الخطوة المناسبة</h2><p>إرسال النموذج لا يعني قبول القضية أو ضمان نتيجة. يتم استخدام البيانات لفهم الطلب وتحديد نطاق الخدمة وطريقة المتابعة المناسبة.</p></div><ol><li><b>1</b><span><strong>إرسال الطلب</strong><small>الاسم والجوال والخدمة والفرع.</small></span></li><li><b>2</b><span><strong>مراجعة أولية</strong><small>فهم الموضوع والمستندات الأساسية.</small></span></li><li><b>3</b><span><strong>تحديد المسار</strong><small>استشارة، صياغة، تفاوض أو تمثيل حسب الحالة.</small></span></li></ol></div></section><section class="cta"><div class="wrap cta-box"><div><span>تحتاج تواصلًا أسرع؟</span><h2>تواصل مع فرع ${x.city} عبر واتساب</h2></div><a class="solid large track-wa" href="https://wa.me/${x.wa}?text=${encodeURIComponent('السلام عليكم، أرغب في استشارة قانونية لدى إتزان - فرع '+x.city)}">فتح واتساب</a></div></section></main>
<footer><div class="wrap footer"><img src="/assets/logo-light.svg" width="160" height="50" alt="إتزان"><p>شركة إتزان للمحاماة والاستشارات القانونية</p><div><a href="https://www.etizan-law.com/privacy" target="_blank" rel="noopener">سياسة الخصوصية</a> · <a class="track-call" href="tel:+${CALL}">اتصال</a></div></div></footer><div class="floating"><a class="float-wa track-wa" href="https://wa.me/${x.wa}?text=${encodeURIComponent('السلام عليكم، أرغب في استشارة قانونية لدى إتزان.')}">واتساب</a><a class="float-call track-call" href="tel:+${CALL}">اتصال</a></div><script>
window.HORIZONS_WA_ATTR={
  clientId:'cl_cbb797950cc8d4',
  businessNumber:'+\${x.wa}',
  endpoint:'https://marketing.hositee.com/wa_click_attribution.php',
  timeoutMs:2500
};
</script>
<script src="https://marketing.hositee.com/horizons-wa-attribution.js?v=1"></script>
<script defer src="/assets/site.js?v=5"></script></body></html>`;
}
module.exports={html,pageData};
